apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: guacamole
  labels:
    app: guacamole
    app.kubernetes.io/component: guacamole
    app.kubernetes.io/instance: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: guacd
  template:
    metadata:
      labels:
        deployment: guacd
    spec:
      volumes:
        - name: freerdp-config
          emptyDir: {}
      containers:
        - name: guacd
          image: guacamole/guacd:1.6.0
          ports:
            - containerPort: 4822
              protocol: TCP
          env:
            - name: HOME
              value: /home/guac
            - name: GUACD_HOSTNAME
              value: 127.0.0.1
            - name: GUACD_PORT
              value: "4822"
            - name: MYSQL_DATABASE
              value: guacamole_db
            - name: MYSQL_HOSTNAME
              value: mysql.guacamole.svc.cluster.local
            - name: MYSQL_PASSWORD
              value: guacamole_pass
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: guacamole_user
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: freerdp-config
              mountPath: /home/guac/.config/freerdp
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
