apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   # adjust the size to what you need
